variables:
  IS_DEPLOY_AGENT: "is-deploy-agent-${CI_COMMIT_TAG}"

stages:
  - build

build:
  stage: build
  image: golang:1.19
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - go build main.go
    - mv main is-deploy-agent
    - tar -zcvf ${IS_DEPLOY_AGENT}.tar.gz is-deploy-agent
    - cp ${IS_DEPLOY_AGENT}.tar.gz ${CI_PROJECT_DIR}
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/${IS_DEPLOY_AGENT}.tar.gz
