name: is-deploy-agent build & deploy

on:
  push:
#    tags:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Go mod tidy
        run: go mod tidy

      - name: Go Build
        run: go build main.go

      - name: Change name
        run: mv main is-deploy-agent

  deploy:
    steps:
      - name: ls
        run: ls -l
#      - name: Upload file to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: /home/runner/work/is-deploy-agent/is-deploy-agent/is-deploy-agent
#          asset_name: is-deploy-agent
#          tag: ${{ github.ref }}
#          overwrite: true
#          body: "new agent"

