name: is-deploy-agent build & deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Go mod tidy
        run: go mod tidy

      - name: Go Build
        run: go build main.go

      - name: Change name
        run: mv main is-deploy-agent

      - name: Tar zip
        run: tar -zcvf is-deploy-agent-${{ github.ref_name }}.tar.gz is-deploy-agent

      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/work/is-deploy-agent/is-deploy-agent/is-deploy-agent-${{ github.ref_name }}.tar.gz
          asset_name: is-deploy-agent-${{ github.ref_name }}.tar.gz
          tag: ${{ github.ref }}
#          overwrite: true
#          body: "new agent"

      -  name: Upload to minio
         uses: lovellfelix/minio-deploy-action@v1
         with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'is-deploy'
          # Optional inputs with their defaults:
          source_dir: /home/runner/work/is-deploy-agent/is-deploy-agent/is-deploy-agent-${{ github.ref_name }}.tar.gz
          target_dir: '/'

